export const GET_DRINKS_CONSUMED_REQUEST = 'DrinksConsumed/GET_DRINKS_CONSUMED_REQUEST'
export const GET_DRINKS_CONSUMED_SUCCESS = 'DrinksConsumed/GET_DRINKS_CONSUMED_SUCCESS'
export const GET_DRINKS_CONSUMED_ERROR = 'DrinksConsumed/GET_DRINKS_CONSUMED_ERROR'
