export const SET_NEW_DRINK = 'NewDrink/SET_NEW_DRINK'
export const SET_NEW_DRINK_QTY = 'NewDrink/SET_NEW_DRINK_QTY'

export const NEW_DRINK_CONSUMED_REQUEST = 'NewDrink/NEW_DRINK_CONSUMED_REQUEST'
export const NEW_DRINK_CONSUMED_SUCCESS = 'NewDrink/NEW_DRINK_CONSUMED_SUCCESS'
export const NEW_DRINK_CONSUMED_ERROR = 'NewDrink/NEW_DRINK_CONSUMED_ERROR'

export const RESET_NEW_DRINK = 'NewDrink/RESET_NEW_DRINK'
